### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by alexximalayaunlv** [ProbstLab/uBin-helperscripts#5]
Hey, I tried to run Example usage for 1 (uBin_wrapper.sh -s scaffolds.fasta -p pdbg -r1 BG_1_S1_L001_interleaved_trim_clean.PE.1.fastq.gz -r2 BG_1_S1_L001_interleaved_trim_clean.PE.2.fastq.gz -e diamond -t 10 -b das_tool_DASTool_scaffolds2bin.txt). 

I encountered following error:
from /home/anaconda3/envs/uBin_input_generator_pyt37/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/anaconda3/envs/uBin_input_generator_pyt37/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- nu (LoadError)

There are kernel_require.rb and kernel_gem.rb under the directory but somehow couldn't be loaded. Do you know what could be the reason?

Thanks!
Alex

**Comment by till-bornemann** [comment]
Hi Alex,

Thank you for trying out uBin. Your ruby version does not seem to find the 'nu' gem. Since this gem is not available via the standard ruby repositories at the required version, we supplied this gem directly within the github repository (the 'nu-2.0.1.gem'  file). You can install this gem directly via (excerpt form the README): 

================
For the gem nu, the required version 2.0.1 is not available in public repositories and thus nu.2.0.1 is supplied as the gem file nu-2.0.1.gem along with the wrapper. You can find the license for the nu gem at https://github.com/bcthomas/mgnu. The gem is installed by the following command:

$ gem install --local nu-2.0.1.gem 
===============

This command assumes that you have loaded the required ruby 2.3 version and that the nu-2.0.1.gem file is in your current directory (otherwise please supply the entire PATH to the gem). 

Could you let me know if this fixes your problem?

Best,
Till
